version: '3.9'
name: '3d_navigation'

services:
  # Global planner service
  global-planner:
    build:
      context: .
      args:
        - BASE_IMG=registry.gitlab.com/beerlab/cpc/utils/cps_ros_base_docker:latest
      cache_from: 
        - registry.gitlab.com/beerlab/cpc/navigation/3d_navigation:latest
    image: registry.gitlab.com/beerlab/cpc/navigation/3d_navigation:latest
    container_name: 3d_navigation
    command: ["/bin/bash", "-ci", "catkin build && source devel/setup.bash && roslaunch 3d_navigation_ros_wrapper global_planner.launch"]
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
    ipc: host
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - ./:/workspace/ros_ws/src/3d_navigation
  # Octomap service
  octomap:
    image: registry.gitlab.com/beerlab/cpc/navigation/3d_navigation:latest
    container_name: octomap
    command: ["/bin/bash", "-ci", "roslaunch octomap_server octomap_tracking_server.launch path:=/workspace/ros_ws/src/3d_navigation/maps/sprint_501.bt"]
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
    ipc: host
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - ./:/workspace/ros_ws/src/3d_navigation
      